spring.application.name=copy-msvc

# Server port
server.port=${SERVER_PORT:8082}

# Database config / Mysql
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:copy_msvc}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# Kafka
spring.cloud.stream.bindings.loanEvents-in-0.destination=loan-events
spring.cloud.stream.bindings.loanEvents-in-0.group=copy-service-group
spring.cloud.stream.kafka.binder.brokers=${KAFKA_BROKER:localhost:9092}

# Feign clients
book-msvc.url=${BOOK_MSVC_URL:http://localhost:8081}