# Resource server
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/library-management-api

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger_test
      use-pkce-with-authorization-code-grant: true
      additional-query-string-params:
        prompt: login