spring.application.name=loan-msvc

# Server port
server.port=${SERVER_PORT:8083}

# Database config / postgres
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:loan_msvc}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# Kafka
spring.cloud.stream.bindings.loan-events-out-0.destination=loan-events
spring.cloud.stream.kafka.binder.brokers=${KAFKA_BROKER:localhost:9092}

# Feign clients
copy-msvc.url=${COPY_MSVC_URL:http://localhost:8082}
user-msvc.url=${USER_MSVC_URL:http://localhost:8084}