spring.application.name=prestamo-msvc

# Database config / postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_msvc
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop