# Gateway
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-msvc
              uri: http://localhost:8081
              predicates:
                - Path=/books/api/v1/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: bookCircuit
                    fallbackUri: forward:/fallback/book
                    statusCodes: [ 500,502,503,504 ]

            - id: copy-msvc
              uri: http://localhost:8082
              predicates:
                - Path=/copies/api/v1/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: copyCircuit
                    fallbackUri: forward:/fallback/copy
                    statusCodes: [ 500,502,503,504 ]

            - id: loan-msvc
              uri: http://localhost:8083
              predicates:
                - Path=/loans/api/v1/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: loanCircuit
                    fallbackUri: forward:/fallback/loan
                    statusCodes: [ 500,502,503,504 ]

            - id: user-msvc
              uri: http://localhost:8084
              predicates:
                - Path=/users/api/v1/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userCircuit
                    fallbackUri: forward:/fallback/user
                    statusCodes: [ 500,502,503,504 ]

# Resource server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/library-management-api

# Resilience
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 7s

  timelimiter:
    configs:
      default:
        timeout-duration: 10s
        cancel-running-future: true