package co.duvan.book.infrastructure.adapters.input.rest.model.response;

import co.duvan.book.domain.enums.Category;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Schema(
        name = "Book Response",
        description = "Book data returned by the API"
)
public class BookResponse {

    @Schema(
            description = "Unique identifier generated by the system for the book",
            example = "1"
    )
    private Long bookId;

    @Schema(
            description = "Title of the book",
            example = "Joyland"
    )
    private String title;

    @Schema(
            description = "Unique identifier of the book in the system",
            example = "ISBN-97"
    )
    private String isbn;

    @Schema(
            description = "Brief summary or description of the book",
            example = "A mystery novel set in an amusement park, written by Stephen King."
    )
    private String description;

    @Schema(
            description = "Category to which the book belongs",
            example = "THRILLER"
    )
    private Category category;

    @Schema(
            description = "List of authors of the book",
            example = "[\"Stephen King\"]"
    )
    private List<String> authors;

    @Schema(
            description = "Name of the publishing company",
            example = "Hard Case Crime"
    )
    private String publisher;
}